---
title: "Data import"
author: "hwj"
date: "2018년 5월 1일"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. txt
## 1.1 separator : blank
```{r}
blank <- read.table(file   = "d:/RBasic/blank.txt",
                    header = TRUE, 
                    sep    = " ")
blank
```
<br>
## 1.2 separator : comma
```{r}
comma <- read.table(file   = "d:/RBasic/comma.txt",
                    header = TRUE, 
                    sep    = ",")
comma
```
<br>
## 1.3 separator : tab
```{r echo=FALSE}
tab <- read.table(file   = "d:/RBasic/tab.txt",
                  header = TRUE, 
                  sep    = "\t")
tab
```
# 2. csv : comma separator value
# 엑셀의 특수한 형태

```{r}
traffic <- read.csv(file   = "d:/RBasic/traffic.csv",
                    header = TRUE)
traffic
```

# 3. excel
```{r}
reading <- readxl::read_excel(path      = "d:/RBasic/reading.xlsx",
                              sheet     = "data",
                              col_names = TRUE)
reading
```

```{r}
reading3 <- readxl::read_excel(path      = "reading.xlsx",
                               sheet     = 1,
                               col_names = TRUE)
reading3
```















